import { Head } from 'next/head'
import { Hero } from '../components/Hero'
import { Layout } from '../components/Layout'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Portfolio Claudia Vásquez</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Hero/> */}
    </Layout>
  )
}
